### PR TITLE
Add apple clang 9.1 job on travis file [build=outdated]

### PR DESCRIPTION
**Pull request by uilianries**

### CODE REVIEW

**Review by theirix — APPROVED** [review]
LGTM, I will merge and update OpenSSL 1.0.2o since 1.0.2n have no 9.1 build

**Comment by uilianries** [comment]
@theirix this is weird because I opened a PR to support 9.1 for OpenSSLn. I'm going to check now.

**Comment by uilianries** [comment]
Now waiting for https://github.com/conan-community/conan-openssl/pull/53

**Comment by theirix** [comment]
you are right, reverted to 1.0.2n after realising how many libraries depend on OpenSSL.
1.0.2n at 9.1 is live now.

**Pull request merged**
